version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
      - image: cimg/postgres:14.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: update apt
          command: sudo apt update
      - run:
          name: install postgresql client
          command: sudo apt install -y postgresql-client
      - run:
          name: create test database
          command: createdb "gicuz" --host localhost --user postgres 
      - run:
          name: Run Tests
          command: npm run test
